# Generated by Django 5.2.5 on 2025-08-26 09:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_sv', models.TextField(default='')),
                ('answer_sv', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('stars', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('form_data', models.JSONField(default=dict)),
                ('paid', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('report_file', models.FileField(null=True, upload_to=app.models.generate_pdf_path)),
                ('otp', models.CharField(default=app.models.create_otp)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('admin_check', models.BooleanField(default=True)),
            ],
        ),
    ]
