# Generated by Django 5.2.8 on 2025-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
