# Generated by Django 5.2.8 on 2025-12-01 04:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_persant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=app.models.random_string, max_length=7, null=True),
        ),
    ]
