# Generated by Django 5.2.8 on 2025-12-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coupon_discount_persant_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_persant',
            new_name='discount',
        ),
    ]
