# Generated by Django 5.2.8 on 2026-01-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_discount_persant_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefinedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[])),
                ('study_level', models.CharField(choices=[])),
                ('org_name', models.TextField()),
                ('munucipality', models.TextField()),
                ('category', models.TextField()),
                ('purpose', models.TextField()),
                ('org_email', models.TextField()),
                ('org_website', models.TextField()),
                ('org_phone', models.TextField()),
                ('org_assets', models.TextField()),
                ('org_main_address', models.TextField()),
                ('org_postal_code', models.TextField()),
                ('org_city', models.TextField()),
                ('org_county', models.TextField()),
            ],
        ),
    ]
