# Generated by Django 5.2.8 on 2026-02-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_predefinedscholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_assets',
            new_name='organization_assets',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_city',
            new_name='organization_city',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_county',
            new_name='organization_county',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_email',
            new_name='organization_email',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_main_address',
            new_name='organization_main_address',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_phone',
            new_name='organization_phone',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_postal_code',
            new_name='organization_postal_code',
        ),
        migrations.RenameField(
            model_name='predefinedscholarship',
            old_name='org_website',
            new_name='organization_website',
        ),
    ]
