# Generated by Django 5.2.8 on 2026-02-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_org_assets_predefinedscholarship_organization_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefinedScholarship_Sv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[])),
                ('study_level', models.CharField(choices=[])),
                ('organization_name', models.TextField()),
                ('munucipality', models.TextField()),
                ('category', models.TextField()),
                ('purpose', models.TextField()),
                ('organization_email', models.TextField()),
                ('organization_website', models.TextField()),
                ('organization_phone', models.TextField()),
                ('organization_assets', models.TextField()),
                ('organization_main_address', models.TextField()),
                ('organization_postal_code', models.TextField()),
                ('organization_city', models.TextField()),
                ('organization_county', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='study_level',
            field=models.CharField(choices=[('universityUndergraduate', 'universityUndergraduate'), ('universityMasters', 'universityMasters'), ('postSecondary', 'postSecondary'), ('upperSecondary', 'upperSecondary'), ('compulsory', 'compulsory'), ('phd', 'phd')]),
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(choices=[('primarySchool', 'primarySchool'), ('secondarySchool', 'secondarySchool'), ('postSecondary', 'postSecondary'), ('university', 'university'), ('master', 'master'), ('phd', 'phd'), ('socialSciences', 'socialSciences'), ('economics', 'economics'), ('naturalSciences', 'naturalSciences'), ('technology', 'technology'), ('arts', 'arts'), ('electricityEnergy', 'electricityEnergy'), ('vehicleTransport', 'vehicleTransport'), ('construction', 'construction'), ('salesService', 'salesService'), ('childRecreation', 'childRecreation'), ('other', 'other'), ('engineering', 'engineering'), ('economics', 'economics'), ('medicine', 'medicine'), ('cs', 'cs'), ('education', 'education'), ('psychology', 'psychology'), ('law', 'law'), ('environment', 'environment'), ('design', 'design'), ('biology', 'biology'), ('publicHealth', 'publicHealth'), ('engineering', 'engineering'), ('business', 'business'), ('cs', 'cs'), ('education', 'education'), ('environment', 'environment'), ('lifeScience', 'lifeScience'), ('law', 'law'), ('design', 'design'), ('socialSciences', 'socialSciences'), ('pharmacyTech', 'pharmacyTech'), ('ambulance', 'ambulance'), ('animalCare', 'animalCare'), ('softwareDev', 'softwareDev'), ('trainDriver', 'trainDriver'), ('dentalNurse', 'dentalNurse'), ('medicalAdmin', 'medicalAdmin'), ('accounting', 'accounting'), ('childcare', 'childcare')]),
        ),
    ]
