# Generated by Django 5.2.8 on 2026-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_predefinedscholarship_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedscholarship',
            name='study_level',
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(choices=[('always', 'always'), ('primarySchool', 'primarySchool'), ('secondarySchool', 'secondarySchool'), ('postSecondary', 'postSecondary'), ('university', 'university'), ('master', 'master'), ('phd', 'phd'), ('socialSciences', 'socialSciences'), ('economics', 'economics'), ('naturalSciences', 'naturalSciences'), ('technology', 'technology'), ('arts', 'arts'), ('electricityEnergy', 'electricityEnergy'), ('vehicleTransport', 'vehicleTransport'), ('construction', 'construction'), ('salesService', 'salesService'), ('childRecreation', 'childRecreation'), ('other', 'other'), ('engineering', 'engineering'), ('medicine', 'medicine'), ('cs', 'cs'), ('education', 'education'), ('psychology', 'psychology'), ('law', 'law'), ('environment', 'environment'), ('design', 'design'), ('biology', 'biology'), ('publicHealth', 'publicHealth'), ('engineering', 'engineering'), ('business', 'business'), ('cs', 'cs'), ('education', 'education'), ('environment', 'environment'), ('lifeScience', 'lifeScience'), ('law', 'law'), ('design', 'design'), ('socialSciences', 'socialSciences'), ('pharmacyTech', 'pharmacyTech'), ('ambulance', 'ambulance'), ('animalCare', 'animalCare'), ('softwareDev', 'softwareDev'), ('trainDriver', 'trainDriver'), ('dentalNurse', 'dentalNurse'), ('medicalAdmin', 'medicalAdmin'), ('accounting', 'accounting'), ('childcare', 'childcare')]),
        ),
    ]
