# Generated by Django 5.2.8 on 2026-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_predefinedscholarship_study_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='pinecone_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='scholarships_db_file',
            field=models.FileField(null=True, upload_to='new_scholarships_db.xlsx'),
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(choices=[('always', 'always'), ('socialSciences', 'socialSciences'), ('economics', 'economics'), ('naturalSciences', 'naturalSciences'), ('technology', 'technology'), ('arts', 'arts'), ('electricityEnergy', 'electricityEnergy'), ('vehicleTransport', 'vehicleTransport'), ('construction', 'construction'), ('salesService', 'salesService'), ('childRecreation', 'childRecreation'), ('other', 'other'), ('engineering', 'engineering'), ('medicine', 'medicine'), ('cs', 'cs'), ('education', 'education'), ('psychology', 'psychology'), ('law', 'law'), ('environment', 'environment'), ('design', 'design'), ('biology', 'biology'), ('publicHealth', 'publicHealth'), ('engineering', 'engineering'), ('business', 'business'), ('cs', 'cs'), ('education', 'education'), ('environment', 'environment'), ('lifeScience', 'lifeScience'), ('law', 'law'), ('design', 'design'), ('socialSciences', 'socialSciences'), ('pharmacyTech', 'pharmacyTech'), ('ambulance', 'ambulance'), ('animalCare', 'animalCare'), ('softwareDev', 'softwareDev'), ('trainDriver', 'trainDriver'), ('dentalNurse', 'dentalNurse'), ('medicalAdmin', 'medicalAdmin'), ('accounting', 'accounting'), ('childcare', 'childcare')]),
        ),
    ]
