# Generated by Django 5.2.8 on 2026-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_siteconfig_pinecone_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='scholarships_db_file',
            field=models.FileField(null=True, upload_to='./new_scholarships_db.xlsx'),
        ),
    ]
