# Generated by Django 5.2.8 on 2026-02-25 09:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_siteconfig_scholarships_db_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='scholarships_db_file',
            field=models.FileField(null=True, upload_to=app.models.scholarship_db_path),
        ),
    ]
