# Generated by Django 5.2.8 on 2026-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_siteconfig_scholarships_db_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='query_template',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default',
            field=models.BooleanField(default=True),
        ),
    ]
