# Generated by Django 5.2.8 on 2026-03-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_siteconfig_query_template_siteconfig_use_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='process_charge',
        ),
    ]
