# Generated by Django 5.2.8 on 2026-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_predefinedscholarship_is_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedscholarship',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'football'), ('athletics', 'athletics'), ('golf', 'golf'), ('gymnastics', 'gymnastics'), ('floorball', 'floorball'), ('ice_hockey', 'ice_hockey'), ('swimming', 'swimming'), ('handball', 'handball'), ('equestrian', 'equestrian'), ('motorsports', 'motorsports')], max_length=50, null=True),
        ),
    ]
