# Generated by Django 5.2.8 on 2026-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_predefinedscholarship_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='sport',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Athletics', 'Athletics'), ('Golf', 'Golf'), ('Gymnastics', 'Gymnastics'), ('Floorball', 'Floorball'), ('Ice Hockey', 'Ice Hockey'), ('Swimming', 'Swimming'), ('Handball', 'Handball'), ('Equestrian', 'Equestrian'), ('Motorsports', 'Motorsports')], max_length=50, null=True),
        ),
    ]
