# Generated by Django 5.2.8 on 2026-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_predefinedscholarship_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'football'), ('athletics', 'athletics'), ('golf', 'golf'), ('gymnastics', 'gymnastics'), ('floorball', 'floorball'), ('ice_hockey', 'ice_hockey'), ('swimming', 'swimming'), ('handball', 'handball'), ('equestrian', 'equestrian'), ('motorsports', 'motorsports')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(blank=True, choices=[('always', 'always'), ('socialSciences', 'socialSciences'), ('economics', 'economics'), ('naturalSciences', 'naturalSciences'), ('technology', 'technology'), ('arts', 'arts'), ('electricityEnergy', 'electricityEnergy'), ('vehicleTransport', 'vehicleTransport'), ('construction', 'construction'), ('salesService', 'salesService'), ('childRecreation', 'childRecreation'), ('other', 'other'), ('engineering', 'engineering'), ('medicine', 'medicine'), ('cs', 'cs'), ('education', 'education'), ('psychology', 'psychology'), ('law', 'law'), ('environment', 'environment'), ('design', 'design'), ('biology', 'biology'), ('publicHealth', 'publicHealth'), ('engineering', 'engineering'), ('business', 'business'), ('cs', 'cs'), ('education', 'education'), ('environment', 'environment'), ('lifeScience', 'lifeScience'), ('law', 'law'), ('design', 'design'), ('socialSciences', 'socialSciences'), ('pharmacyTech', 'pharmacyTech'), ('ambulance', 'ambulance'), ('animalCare', 'animalCare'), ('softwareDev', 'softwareDev'), ('trainDriver', 'trainDriver'), ('dentalNurse', 'dentalNurse'), ('medicalAdmin', 'medicalAdmin'), ('accounting', 'accounting'), ('childcare', 'childcare'), ('sport', 'sport')], null=True),
        ),
    ]
