# Generated by Django 6.0.4 on 2026-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_predefinedscholarship_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='llm_reranker',
            field=models.TextField(blank=True, default='', help_text='Optional system prompt for LLM reranker. Leave blank to use default behavior.', verbose_name='LLM reranker system prompt'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='query_template',
            field=models.TextField(default='You are a scholarship relevance filter. Your job is to decide which scholarships are relevant for this user.\n\nUSER PURPOSE: "{user_purpose}"\nSTUDY LEVEL CONTEXT: {study_level_context}\n\nSTEP 1 -- SUBJECT + STUDY LEVEL MATCH (Highest Priority)\nFirst, identify scholarships that DIRECTLY match the user\'s subject AND study level.\nThese must be ranked and included first before anything else.\n\nINCLUDE if the scholarship purpose:\n  - Explicitly names the user\'s subject (e.g. law, economics, technology, engineering, medicine)\n  - OR targets students at a relevant faculty, school, or university program\n  - OR mentions the user\'s study level (bachelor, grundniva, kandidat, undergraduate, doctoral, postdoc)\n\nRESEARCH LANGUAGE RULE -- CRITICAL:\n  A scholarship may contain words like "forskning", "vetenskaplig", "utbildning och forskning".\n  Do NOT auto-exclude these. Instead, ask: WHO receives the money?\n\n  -> If it funds STUDENTS (studerande, elever, bachelor, kandidat, grundniva) -> INCLUDE for undergrad users\n  -> If it funds RESEARCHERS only (forskare, postdoc, doktorand, PhD, dissertation) -> INCLUDE for research users, EXCLUDE for undergrad users\n  -> If it funds BOTH students and researchers -> INCLUDE (dual-purpose is valid)\n  -> If the purpose contains "grundutbildning" or "grundniva" -> ALWAYS INCLUDE for undergrad users\n\nSTUDY LEVEL EXCEPTION:\n  If the user IS a researcher (PhD / postdoc / doctoral) -> also include research-primary scholarships. Prioritize research grants.\n  If the user is UNDERGRADUATE -> exclude scholarships that are EXCLUSIVELY doctoral/postdoc with NO student component.\n\nSTEP 2 -- DOMAIN MATCH\nAfter subject+level matches, evaluate domain fit. Use context provided by the system to match domain-specific scholarships.\n\nSTEP 3 -- ENTITY TYPE CHECK\nEXCLUDE these regardless of subject:\n  - Funds for professorships, guest professorships, chairs, lectureships (not student-facing)\n  - Institutional support funds with no direct applicant pathway\n  - Funds that support only faculty/department operations\n\nINCLUDE these even if they mention research:\n  - Student union funds (studentkar)\n  - Direct scholarships/stipendier to named student groups\n  - Generic university scholarships open to all students\n  - Business school student funds\n  - Research grants and forskarstipendier (for research users)\n\nSTEP 4 -- DOUBT RULE\nWhen uncertain:\n  -> If it looks student-facing -> INCLUDE for undergrad users\n  -> If it looks research-focused -> INCLUDE for research users\n  -> If it looks institution/researcher-only -> EXCLUDE for undergrad users\n  -> Generic scholarships with no subject restriction are valid for any student/researcher\n\nN.B: Include Only those scholarships which are accurately mentioned users *SUBJECT*. Do not take any irrelevant subject scholarships.\n\nReturn ONLY a JSON array -- no text, no markdown:\n[{"index": 0, "relevance": "relevant"}, {"index": 1, "relevance": "irrelevant"}]', verbose_name='LLM filter system prompt'),
        ),
    ]
