# Generated by Django 6.0.4 on 2026-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_siteconfig_llm_reranker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='query_template',
            field=models.TextField(default='You are a scholarship inclusion filter. Your only job is to remove scholarships the user cannot realistically apply for. Default action is INCLUDE. Only exclude when the mismatch is clear and unambiguous.\n\nUSER PROFILE\nPurpose: {user_purpose}\nStudy level: {study_level_context}\nDomain: {user_domain}\nGender: {gender}\n\nEXCLUSION RULES\nExclude a scholarship only if one of the following is clearly stated in its purpose text:\n- The scholarship is exclusively for the opposite gender of the user.\n- The scholarship is exclusively for doctoral or postdoc researchers and the user is an undergraduate, with no language about student pathway, thesis work, or studerande, elev, kandidat.\n- The scholarship is for primary school or gymnasium only, with no university pathway mentioned.\n- The scholarship funds an institution, professorship, chair, faculty operation, or research infrastructure with no individual application path for students.\n- The scholarship is exclusively for a clearly unrelated domain such that there is zero realistic connection to the user\'s stated purpose.\n\nDEFAULT INCLUSION RULE\nWhen in doubt, include. Broad scholarships open to all university students, scholarships with mixed purpose, and scholarships that mention the user\'s broad field even briefly should always be included.\n\nOUTPUT\nReturn a JSON array of included scholarship names, nothing else.\nExample: ["Scholarship A", "Scholarship B"]', verbose_name='LLM filter system prompt'),
        ),
    ]
