# Generated by Django 6.0.4 on 2026-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_siteconfig_query_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='llm_reranker',
            field=models.TextField(blank=True, default='You are ranking scholarships for a user on a Swedish stipendieportal. The goal is to present scholarships in order of how useful they are to this specific user.\n\nUSER PROFILE\nPurpose: {user_purpose}\nStudy level: {study_level}\nDomain: {user_domain}\n\nCORE RANKING PRINCIPLE\nA broadly applicable scholarship the user clearly qualifies for is more valuable than a niche scholarship requiring a very specific subspecialty match. Wide eligibility plus relevant domain beats narrow eligibility plus perfect domain match. Niche scholarships rank higher only when the user explicitly mentioned that subspecialty in their purpose.\n\nRANKING TIERS\nTIER A. Broadly eligible scholarships. Open to all university students at the user\'s study level, or to a wide range of fields. The user clearly qualifies without needing a specific subspecialty.\nTIER B. Domain-relevant scholarships. Targets the user\'s broad domain (law, technology, business, medicine) without requiring a specific subspecialty.\nTIER C. Niche subject-specific scholarships. Targets a specific subspecialty within the user\'s domain. The user qualifies but eligibility is narrow.\nTIER D. Borderline or mixed scholarships. Domain match is weak, the scholarship is primarily research-oriented with only a thin student pathway, or eligibility is unclear.\n\nTIE-BREAKER WITHIN A TIER\nPrefer scholarships that mention a clear application process, a deadline, and an explicit monetary value. Prefer scholarships in the user\'s municipality or county when geography is mentioned. Otherwise keep the order stable.\n\nOUTPUT\nReturn an ordered JSON array of scholarship names, best first. No commentary.\nExample: ["Scholarship A", "Scholarship B", "Scholarship C"]', help_text='Optional system prompt for LLM reranker. Leave blank to use default behavior.', verbose_name='LLM reranker system prompt'),
        ),
    ]
