# Generated by Django 6.0.4 on 2026-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_update_siteconfig_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_query_prompt_individual',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM filter when user type is Individual. Leave blank to use the default prompt above.', verbose_name='Custom LLM Filter Prompt - Individual Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_query_prompt_organization',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM filter when user type is Organization. Leave blank to use the built-in organization prompt.', verbose_name='Custom LLM Filter Prompt - Organization Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_reranker_prompt_individual',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM reranker when user type is Individual. Leave blank to use the default prompt above.', verbose_name='Custom LLM Reranker Prompt - Individual Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_reranker_prompt_organization',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM reranker when user type is Organization. Leave blank to use the built-in organization prompt.', verbose_name='Custom LLM Reranker Prompt - Organization Users'),
        ),
    ]
