# Generated by Django 6.0.4 on 2026-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_siteconfig_custom_query_prompt_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_base',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt', verbose_name='Use Default - LLM Filter Base Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_individual',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt for individual users', verbose_name='Use Default - Individual Filter Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_organization',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt for organization users', verbose_name='Use Default - Organization Filter Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_base',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt', verbose_name='Use Default - LLM Reranker Base Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_individual',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt for individual users', verbose_name='Use Default - Individual Reranker Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_organization',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt for organization users', verbose_name='Use Default - Organization Reranker Prompt'),
        ),
    ]
