# Generated by Django 6.0.4 on 2026-05-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_siteconfig_active_dataset_index_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedscholarship',
            name='study_level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate/Bachelor'), ('master', "Master's"), ('phd', 'PhD/Doctoral'), ('all', 'All Levels')], default='all', help_text='Target study level for this scholarship', max_length=50, null=True),
        ),
    ]
