# Generated by Django 6.0.4 on 2026-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_siteconfig_last_active_dataset_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('other', 'Other'), ('engineering_technology', 'Engineering and Technology'), ('economics_business', 'Economics, Business Administration & Management'), ('medicine_health', 'Medicine and Health Sciences'), ('cs_it_data', 'Computer Science / IT / Data Science'), ('education_pedagogy', 'Education and Pedagogy'), ('psychology_behavioral', 'Psychology and Behavioral Sciences'), ('law_political', 'Law and Political Science'), ('environment_sustainability', 'Environmental and Sustainability Sciences'), ('design_architecture_arts', 'Design, Architecture, and Creative Arts'), ('biology_chemistry_life', 'Biology, Chemistry, and Life Sciences'), ('public_health_epidemiology', 'Public Health / Epidemiology'), ('eng_tech_advanced', 'Engineering & Technology (cybersecurity, supply chain, machine)'), ('business_management', 'Business & Management (Finance, Accounting, International Business)'), ('cs_digital_data_advanced', 'Computer Science / Digital Business / Data Science'), ('education_didactics', 'Education & Pedagogy (Didactics, Leadership)'), ('environment_urban', 'Environmental & Sustainability Sciences / Urban Planning'), ('life_science_biotech', 'Life Sciences & Biotechnology'), ('law_llm', 'Law (LL.M / Legal Studies)'), ('design_creative_advanced', 'Design, Architecture & Creative Arts'), ('social_sciences', 'Social Sciences (Psychology, Social Work, Political Science)'), ('phd_engineering_technology', 'Engineering/Technology | Teknik och ingenjörsvetenskap'), ('phd_economics', 'Economics | Ekonomi'), ('phd_medicine', 'Medicine | Medicin'), ('phd_law', 'Law | Juridik'), ('phd_arts_culture', 'Arts/Culture | Konst/Kultur')], null=True),
        ),
    ]
