# Generated by Django 6.0.4 on 2026-06-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_coupon_tracking'),
        ('app', '0032_alter_predefinedscholarship_subject'),
    ]

    operations = [
    ]
