# Generated by Django 6.0.4 on 2026-06-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_20260607_1200'),
        ('app', '0033_remove_incomplete_sv_model'),
    ]

    operations = [
    ]
