# Generated by Django 6.0.6 on 2026-06-17 03:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20260608_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='pdf_created_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was generated. Used for 24-hour auto-deletion.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=app.models.random_string, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplicant',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.generate_pdf_path),
        ),
    ]
