# Generated by Django 6.0.4 on 2026-06-28 05:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20260608_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='otp_email_body_en',
            field=models.TextField(default='Hello,\n\nUse this OTP code to continue your scholarship search:\n\n{otp}\n\nThank you.\n', help_text='Use {otp} to insert the one-time passcode.', verbose_name='OTP Email Body (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='otp_email_body_sv',
            field=models.TextField(default='Hej,\n\nAnvänd denna OTP-kod för att fortsätta din stipendiesökning:\n\n{otp}\n\nTack.\n', help_text='Use {otp} to insert the one-time passcode.', verbose_name='OTP Email Body (SV)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='otp_email_subject_en',
            field=models.CharField(default='Your scholarship OTP code', max_length=255, verbose_name='OTP Email Subject (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='otp_email_subject_sv',
            field=models.CharField(default='Din OTP-kod för stipendiesökning', max_length=255, verbose_name='OTP Email Subject (SV)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='report_email_body_en',
            field=models.TextField(default='Hello,\n\nYour scholarship report is attached. Please review the attached file for the matching scholarships.\n\nReport file: {report_file_name}\n\nBest regards,\nScholarship team\n', help_text='Use {report_file_name} to insert the attached report file name.', verbose_name='Report Email Body (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='report_email_body_sv',
            field=models.TextField(default='Hej,\n\nDin stipendierapport är bifogad. Granska den bifogade filen för matchade stipendier.\n\nRapportfil: {report_file_name}\n\nVänliga hälsningar,\nStipendieteamet\n', help_text='Use {report_file_name} to insert the attached report file name.', verbose_name='Report Email Body (SV)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='report_email_subject_en',
            field=models.CharField(default='Your scholarship report is ready', max_length=255, verbose_name='Report Email Subject (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='report_email_subject_sv',
            field=models.CharField(default='Din stipendierapport är klar', max_length=255, verbose_name='Report Email Subject (SV)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=app.models.random_string, max_length=7, null=True, unique=True),
        ),
    ]
