# Generated by Django 6.0.4 on 2026-07-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_add_email_template_fields'),
        ('app', '0035_scholarshipapplicant_pdf_created_at_and_more'),
    ]

    operations = [
    ]
