# Generated by Django 6.0.4 on 2026-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_siteconfig_last_active_dataset_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='upload_error_message',
            field=models.TextField(blank=True, help_text='If the upload fails, a short error message is recorded here.', null=True, verbose_name='Upload error message'),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='upload_progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Integer percent progress (0-100) updated during background uploads.', verbose_name='Upload Progress (%)'),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='upload_rows_total',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rows in the dataset when upload started.', null=True, verbose_name='Total rows'),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='upload_rows_uploaded',
            field=models.PositiveIntegerField(default=0, help_text='Number of rows successfully uploaded to the index.', verbose_name='Rows uploaded'),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('index_created', 'Index Created'), ('partial', 'Partial Upload'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='High-level status of the dataset upload to Pinecone.', max_length=32, verbose_name='Upload Status'),
        ),
    ]
